FORMAT: 1A
HOST: https://brein-service.herokuapp.com/api

# brein API

Brein API controlls the database of brein.

## Users [/users]

A User object has the following attributes:

+ username (required)
+ password (required)
+ names (required)
+ lastnames (required)
+ birthyear
+ email

### Get all users [GET]

+ Response 200 (application/json)

        {
          "testuser": {
            "birthyear": 1998,
            "email": "pedro@test.com",
            "lastnames": "Navajas",
            "names": "Pedro",
            "password": "MTIzNA==",
            "username": "testuser"
          },
          "testuser2": {
            "birthyear": 1991,
            "email": "jdtorregrosas@gmail.com",
            "lastnames": "Torregrosa",
            "names": "Julian",
            "password": "MTIz",
            "username": "testuser2"
          }
        }

### Create a user [POST]

+ Request (application/json)

        {
          "username": "cmatorresa",
          "password": "mateloco",
          "names": "Mateo",
          "lastnames": "Torregrosa",
          "birthyear": 1998,
          "email": "mate@test.com"
        }

+ Response 200 (application/json)

        {
          "username": "testUser",
          "password": "1234",
          "names": "Pedro",
          "lastnames": "Navajas",
          "birthyear": 1998,
          "email": "pedro@test.com"
        }

+ Response 409 (application/json)

        {
          "error": "User already exists"
        }

### Get single user [GET /users/{username}]

+ Parameters
    + username: testUser (required, string) - Username of the user

+ Response 200 (application/json)

        {
          "username": "testUser",
          "password": "1234",
          "names": "Pedro",
          "lastnames": "Navajas",
          "birthyear": 1998,
          "email": "pedro@test.com"
        }

+ Response 404 (application/json)

        {
          "error": "User not found"
        }

### Update a user [PUT /users/{username}]

+ Parameters
    + username: testUser (required, string) - Username of the user

+ Request (application/json)

        {
          "names": "Mateo",
          "lastnames": "Torregrosa",
          "birthyear": 1998,
          "email": "mate@test.com"
        }

+ Response 200 (application/json)

        {
          "username": "testUser",
          "password": "1234",
          "names": "Pedro",
          "lastnames": "Navajas",
          "birthyear": 1998,
          "email": "pedro@test.com"
        }

+ Response 404 (application/json)

        {
          "error": "User not found"
        }
